name: Luna Debug APK Builder
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Debug APK
        run: |
          ./gradlew wrapper  # Bu komut gradlew dosyanı yoksa oluşturur
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Luna-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
